# -*- coding: utf-8 -*-
"""Student.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Di9NJxfyAUZZokF9XgTbuhO8ankO1hxS
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv("StudentsPerformance.csv")

df.head()

df.tail()

df.describe()

df.shape

df.columns

df.info

df.describe()

df.isnull().sum()

df.duplicated().sum()

score_columns = ['math score', 'reading score', 'writing score']
df[score_columns].describe()

df[score_columns].mean()

df[score_columns].median()

df[score_columns].mode()

df[score_columns].quantile(0.25)

df[score_columns].quantile(0.50)

df[score_columns].quantile(0.75)

df["total score"] = df["math score"] + df["reading score"] + df["writing score"]

df.columns

df["Percentage"]=(df['total score']/300)*100

df[["total score","Percentage"]].head()